<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <TheForgeRoot>$([System.IO.Path]::GetFullPath("$(MSBuildThisFileDirectory)..\..\..\"))</TheForgeRoot>
    <TheForgeArtDir>$([System.IO.Path]::GetFullPath("$(TheForgeRoot)Art\"))</TheForgeArtDir>
    <CustomMiddlewareRoot>$([System.IO.Path]::GetFullPath("$(TheForgeRoot)..\Custom-Middleware\"))</CustomMiddlewareRoot>
    <ISPCDir>$([System.IO.Path]::GetFullPath("$(TheForgeRoot)Common_3/Tools/ThirdParty/OpenSource/ISPCTextureCompressor/ISPC/"))</ISPCDir>
    <UsingMSVC>false</UsingMSVC>
    <UsingMSVC Condition="'$(Platform)'=='x64'">true</UsingMSVC>
    <UsingMSVC Condition="'$(Platform)'=='ARM64'">true</UsingMSVC>
    <UsingMSVC Condition="'$(Platform)'=='Gaming.Xbox.XboxOne.x64'">true</UsingMSVC>
    <UsingMSVC Condition="'$(Platform)'=='Gaming.Xbox.Scarlett.x64'">true</UsingMSVC>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <PreBuildEvent>
      <Command>
if not exist "$(IntDir)ISPC" (
  mkdir "$(IntDir)ISPC";
)
if not exist "$(IntDir)Headers" (
  mkdir "$(IntDir)Headers";
)
if not exist "$(IntDir)Headers/C" (
  mkdir "$(IntDir)Headers/C";
)
if not exist "$(IntDir)ISPC" (
  mkdir "$(IntDir)ISPC";
)
if exist "$(IntDir)ISPC\objlist.rsp" (
  del /q "$(IntDir)ISPC\objlist.rsp"
)
type NUL > "$(IntDir)ISPC\objlist.rsp"

%(Command)
      </Command>
    </PreBuildEvent>
	  <PreLinkEvent>
      <Command>
setlocal EnableDelayedExpansion

:: Put all obj's in the directory in a link response file with forward slashes
:: BEWARE: If file contains backslashes, visual studio will internally break and just print a C# exception with no clue whatsoever to what the problem is. This took me days to debug.
for %%f in ("$(IntDir)ISPC\*.o") do (
    set "file=%%~f"
    set "file=!file:\=/!"
    echo "!file!" >> "$(IntDir)ISPC\objlist.rsp"
)

%(Command)
	    </Command>
	  </PreLinkEvent>
	  <PreLinkEvent Condition="$(ProjectDir.Contains('Switch'))">
      <Command>
:: On Switch, we need to work around a internal SDK bug by manually linking the obj's into a static library first

if not exist "$(IntDir)ISPC" (
    mkdir "$(IntDir)ISPC"
)

:: Make a dummy objlist.a in case we have nothing to link
echo int __dummy = 0; > dummy.c
"$(NINTENDO_SDK_ROOT)\Compilers\NintendoClang\bin\clang.exe" -c dummy.c -o dummy.o --target=aarch64-nintendo-nx-elf
"$(NINTENDO_SDK_ROOT)\Compilers\NintendoClang\bin\llvm-ar.exe" rcs "$(IntDir)ISPC\objlist.a" dummy.o
"$(NINTENDO_SDK_ROOT)\Compilers\NintendoClang\bin\llvm-ar.exe" d "$(IntDir)ISPC\objlist.a" dummy.o
del dummy.c dummy.o

if exist "$(IntDir)ISPC\*.o" (
    for /R "$(IntDir)ISPC" %%f in (*.o) do (
        "$(NINTENDO_SDK_ROOT)\Compilers\NintendoClang\bin\llvm-ar.exe" rc "$(IntDir)ISPC\objlist.a" "%%f"
    )
    "$(NINTENDO_SDK_ROOT)\Compilers\NintendoClang\bin\llvm-ar.exe" s "$(IntDir)ISPC\objlist.a"
)
	  %(Command)
	  </Command>
	  </PreLinkEvent>
    <ClCompile>
      <ConformanceMode>true</ConformanceMode>
      <RuntimeTypeInfo>false</RuntimeTypeInfo>
      <ExceptionHandling>false</ExceptionHandling>
      <PreprocessorDefinitions>_HAS_EXCEPTIONS=0;$(AdditionalForgeDefines);%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalIncludeDirectories>$(IntDir)Headers/C;$(OSIntDir)Headers/C;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <DebugInformationFormat>OldStyle</DebugInformationFormat>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
      <ForcedIncludeFiles>%(ForcedIncludeFiles)</ForcedIncludeFiles>
      <TreatWarningAsError>true</TreatWarningAsError>
      <WarningsAsErrors>true</WarningsAsErrors>
      <WarningLevel Condition="!$(UsingMSVC)">EnableWarnings</WarningLevel>
      <WarningLevel Condition="$(UsingMSVC)">Level4</WarningLevel>
      <DisableSpecificWarnings Condition="$(UsingMSVC)">4201;4324;4127%(DisableSpecificWarnings)</DisableSpecificWarnings>
    </ClCompile>
    <Link Condition="$(UsingMSVC)">
      <AdditionalDependencies>"$(IntDir)ISPC\*.o";"$(OSIntDir)ISPC\*.o";%(AdditionalDependencies)</AdditionalDependencies>
      </Link>
    <Link Condition="!$(UsingMSVC) and !$(ProjectDir.Contains('NX'))">
    <!-- ISPCRuntime.o won't be included in .so files causing error when linking to ISPC .o files, since they use symbols like ISPCLaunch, ISPCSync, ISPCAlloc -->
    <AdditionalOptions>-Wl,--undefined=ISPCAlloc</AdditionalOptions>
		<AdditionalDependencies>@$(IntDir)ISPC/objlist.rsp;@$(OSIntDir)ISPC/objlist.rsp;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
	<!-- Link to the manualy generated static library on NX to work around bug -->
	<Link Condition="$(ProjectDir.Contains('NX'))">
		<AdditionalDependencies>$(OSIntDir)ISPC/objlist.a;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
	<Link Condition="$(ProjectDir.Contains('NX'))">
	  <AdditionalDependencies>$(IntDir)ISPC/objlist.a;%(AdditionalDependencies)</AdditionalDependencies>
	</Link>
  </ItemDefinitionGroup>
  <PropertyGroup Condition="'$(Platform)' == 'x64'">
    <!-- Update to change the SDK version -->
    <D3D12AgilitySdkVersion>715</D3D12AgilitySdkVersion>
    <UsePreviewAgility>false</UsePreviewAgility>
    <!-- Update if the newer preview SDK version is required -->
    <UsePreviewAgility Condition="'$(D3D12AgilitySdkVersion)'=='717'">true</UsePreviewAgility>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Platform)' == 'x64'">
    <ClCompile>
      <!-- When updating the sdk, you should only need to change the values in this file, and to copy the DLLs in the game/pc/D3D12 directory -->
      <!-- General -->
      <PreprocessorDefinitions>
        D3D12_AGILITY_SDK=1;
        D3D12_AGILITY_SDK_VERSION=$(D3D12AgilitySdkVersion);
        USE_PREVIEW_AGILITY=$(UsePreviewAgility);
        %(PreprocessorDefinitions)
      </PreprocessorDefinitions>
    </ClCompile>
  </ItemDefinitionGroup>
  <ImportGroup Label="PropertySheets">
    <Import Condition="$(ProjectDir.Contains('Quest_VS2019'))" Project="$(TheForgeRoot)Examples_3\Build_Props\VS\Quest.arm64.v8a.props" />
    <Import Condition="$(ProjectDir.Contains('Android_VS2019'))" Project="$(TheForgeRoot)Examples_3\Build_Props\VS\Android.arm64.v8a.props" />
    <Import Condition="$(ProjectDir.Contains('PC_VS2019'))" Project="$(TheForgeRoot)Examples_3\Build_Props\VS\Examples.x64.props" />
    <Import Condition="$(ProjectDir.Contains('PS4_VS2019'))" Project="$(TheForgeRoot)PS4\VSProps\PS4.props" />
    <Import Condition="$(ProjectDir.Contains('Prospero_VS2019'))" Project="$(TheForgeRoot)Prospero\VSProps\Prospero.props" />
    <Import Condition="$(ProjectDir.Contains('NX'))" Project="$(TheForgeRoot)Switch\Examples_3\Unit_Tests\NX_VS2019\ImportNintendoSdk.props" />
  </ImportGroup>
  <PropertyGroup Condition="$(ProjectDir.Contains('Quest_VS2019'))">
    <TargetOS>Android</TargetOS>
    <OSIntDir>$(SolutionDir)$(Platform)\$(Configuration)\OS\$(PlatformTarget)\Intermediate\</OSIntDir>
  </PropertyGroup>
  <PropertyGroup Condition="$(ProjectDir.Contains('Android_VS2019')) or $(ProjectDir.Contains('AndroidVisualStudio2019'))">
    <TargetOS>Android</TargetOS>
    <OSIntDir>$(SolutionDir)$(Platform)\$(Configuration)\OS\$(PlatformTarget)\Intermediate\</OSIntDir>
  </PropertyGroup>
  <PropertyGroup Condition="$(ProjectDir.Contains('PC_VS2019')) or $(ProjectDir.Contains('Win64'))">
    <TargetOS>Windows</TargetOS>
    <OSIntDir>$(SolutionDir)$(Platform)\$(Configuration)\Intermediate\OS\</OSIntDir>
  </PropertyGroup>
  <PropertyGroup Condition="$(ProjectDir.Contains('PS4_VS2019')) or $(ProjectDir.Contains('Orbis')) or $(ProjectDir.Contains('PS4'))">
    <TargetOS>PS4</TargetOS>
    <OSIntDir>$(SolutionDir)$(Platform)\$(Configuration)\Intermediate\OS\</OSIntDir>
  </PropertyGroup>
  <PropertyGroup Condition="$(ProjectDir.Contains('Prospero'))">
    <TargetOS>PS5</TargetOS>
    <OSIntDir>$(SolutionDir)$(Platform)\$(Configuration)\Intermediate\OS\</OSIntDir>
  </PropertyGroup>
  <PropertyGroup Condition="$(ProjectDir.Contains('NX_VS2019')) or $(ProjectDir.Contains('Switch'))">
    <TargetOS>Switch</TargetOS>
    <OSIntDir>$(SolutionDir)$(Platform)\OS\$(Configuration)\Intermediate\</OSIntDir>
  </PropertyGroup>
  <PropertyGroup Condition="$(ProjectDir.Contains('XBOX_VS2019')) or $(ProjectDir.Contains('Xbox'))">
    <TargetOS>Xbox</TargetOS>
    <OSIntDir>$(TheForgeRoot)Xbox\Examples_3\Unit_Tests\XBOX_VS2019\Libraries\OSBase\$(Platform)\$(Configuration)\</OSIntDir>
  </PropertyGroup>
  
  
  <PropertyGroup>
    <NoWarn>$(NoWarn);MSB8018</NoWarn>
  </PropertyGroup>
</Project>
